# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - release-php-84

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.4'

  #     - name: Check if composer.json exists
  #       id: check_files
  #       uses: andstor/file-existence-action@v1
  #       with:
  #         files: 'composer.json'

  #     - name: Run composer install if composer.json exists
  #       if: steps.check_files.outputs.files_exists == 'true'
  #       run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: php-app
  #         path: .
          

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   permissions:
  #     id-token: write #This is required for requesting the JWT
  #     contents: read #This is required for actions/checkout

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: php-app

  #     - name: Some Check
  #       run: |
  #         ls -al
  #         touch abc.war
      
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88E784C5ABA64C2A8DB481895BD28AF0 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_09F123B9D19542B3A1AD1A507BFC84DE }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_77227E0F20844EABBB184E458427A6F1 }}

  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v3-release-zip-archival-fix
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'release-php-84'
  #         slot-name: 'Production'
  #         package: .
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress
  
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'release-php-vsts'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          
